### Test Health Check
GET http://localhost:5001/api/health

### Test Supabase Connection
GET http://localhost:5001/api/supabase-test

### Test User Signup (Change email if you run it multiple times!)
POST http://localhost:5001/api/auth/signup
Content-Type: application/json

{
  "email": "testing789@myapp.com",
  "password": "securepassword",
  "fullName": "REST Client Tester"
}

### Login to get Access Token
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "testing789@myapp.com",
  "password": "securepassword"
}

### Test File Upload (NEEDS A REAL TOKEN!)
POST http://localhost:5001/api/documents/upload
Authorization: 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test_notes2.txt"
Content-Type: text/plain

This is a test document.
It contains some super important secrets.
Hushh!
------WebKitFormBoundary7MA4YWxkTrZu0gW--
